on:
  pull_request

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.pull_request) }}
        run: echo "$GITHUB_CONTEXT"
